name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Wallysson
          outputs: dist/github-snake.svg

      - name: Commit and Push Changes
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: 'dist'
          destination-github-username: Wallysson
          destination-repository-name: Wallysson
          user-email: wlc.couto@gmail.com
          commit-message: "Generated snake animation"
          target-branch: output
