name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Wallysson  # Your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Create output directory if it doesn't exist
        run: mkdir -p dist

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist

      - name: Check generated file
        run: ls -la dist/github-contribution-grid-snake.svg
